apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  containers:
  - name: test-container
    image: busybox
    command: ['sh', '-c', 'echo "Username: $USERNAME, Password: $PASSWORD" && sleep 3600']
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: used-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: used-secret
          key: password
  restartPolicy: Never